### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by khaledhaf** [arya1106/NappyTime14#1]
Hello,
Can you please add an option that display Countdown always below the date on the lockscreen, (same as the picture below) Thanks.
![image](https://user-images.githubusercontent.com/33642208/109946846-bf154b00-7ce9-11eb-95aa-53e28ddf6749.jpeg)

**Comment by arya1106** [comment]
Hi, this feature is in the works and will be pushed in the next update!

**Comment by arya1106** [comment]
This feature was pushed in the latest update, closing the issue now.
