### ISSUE TITLE
Countdown turns blue?

### ISSUE THREAD

**Issue by L0rdLogan** [arya1106/NappyTime14#2]
The countdown on the lockscreen will sometimes randomly turn blue for seemingly no reason at all

**Comment by L0rdLogan** [comment]
> Could you provide some more information? A screenshot or a list of installed tweaks would help a lot.

Next time it happens, I will.

**Comment by L0rdLogan** [comment]
Okay. So it happened ![image](https://user-images.githubusercontent.com/5092548/114343017-ea931d00-9b54-11eb-8812-5e23e405165f.png)

Installed tweaks:
7-zip (POSIX): 17.03
APFS Snapshot Utility: 10.15.1
Alive: 1.2.7
AnsweringMachine XS: 1.2-61
AppData: 1.3.6
AppList: 1.5.16
AppSync Unified: 92.0
AudioRecorder XS (iOS 12/13/14): 3.7-42
AutoUnlockX: 1.0.16
Base Structure: 1-5
BioProtect XS (iOS 12/13/14): 4.5-14
CA Certs: 0.0.3
CC On & Off: 0.0.1.1
CCPower: 1.8-1
CCSupport: 1.3.3
CallBar XS (iOS 12/13/14): 4.0-127
Cephei Tweak Support: 1.16
Cercube for YouTube: 5.2.15
Core Utilities: 8.32-9
Cr4shed: 4.2.2
Darwin Tools: 1.3
Debian Packager: 1.20.7.1
Debian Utilities: 4.11.2
Diff Utilities: 3.7-2
Dress 👗: 2.5.10
Essential: 0-4
Filza File Manager: 3.8.1-29
Find Utilities: 4.8.0
Hestia: 1.0.1
InstaNotAStalker: 1.0
Jailbreak Updater: 1.0
Koi 🐠: 1.1.5
Launch Daemon Controller: 23-3
LocationService (CCSupport): 0.1-4-1
LockShut: 1.1.1
Lyricify: 2.1.3
MKTBypass: 1.1.3
MYbloXX for iOS (13+): 2.040821-13
Messenger No Ads: 3.10.0
NappyTime14: 1.1.2
NewTerm 2: 2.5
OTADisabler: 0.1-9
OpenSSL 1.1.x Libraries: 1.1.1k
PreferenceLoader: 3.0.3
Procursus APT Keyring: 2020.05.09
Profile Directory: 0-6
RoadRunner: 1.0~beta4
RocketBootstrap: 1.1.0~libhooker2
Safe Mode (libhooker): 1.1.4
SecretShot: 1.1
Sileo: 2.0.3
SimpleActivationActions: 0.1-1
SnowBoard: 1.4.12~Beta4
Springtomize 5: 5.2.3
Stalky: 4.1.7
Sudo: 1.9.6p1-2
System Info: 2.7.2-2
TikTok God: 1.12.2
TweakReviewsDB: 0.7.1
Twitter No Ads: 1.4.0
UIKit Tools: 2.0.3
UnlockVol13: 0.0.1
Watusi 3 for WhatsApp: 0.10.3
WatusiTools: 2.2.3
Weather Plus: 1.1.0
Z Shell: 5.8-4
apt: 2.3.0-1
bash: 5.1.004-3
dash: 0.5.11.3-1
diskdev-cmds: 667.40.1
file-cmds: 287.40.2-1
gettext-localizations: 2020.10.07
gpgv: 2.2.27-1
grep: 3.6
gzip: 1.10-2
iCleaner Pro: 7.9.1
iOS Firmware: 14.3
iPhone Firmware (/sbin): 0-1
iSecureOS: 1.20
libCSPreferences: 1.4.8
libKitten 🐱: 1.2.1
libMRYIPC: 2.0.1
libSparkAppList: 1.0.10
libapt-pkg6.0: 2.3.0-1
libbulletin: 0.1-158
libcrypt2: 4.4.17
libedit0: 3.1-20191231
libffi7: 3.3-1
libgcrypt20: 1.9.1
libgmp10: 6.2.1-1
libgnutls30: 3.7.1
libgpg-error0: 1.42
libhdev: 4.8.0
libhogweed6: 3.6
libhooker: 1.6.0
libhooker Configurator: 1.1.1-1
libidn2-0: 2.3.0-3
libintl8: 0.21-4
liblua5.3-0: 5.3.3-1
liblz4-1: 1.9.2-2
liblzma5: 5.2.5-2
libmd0: 1.0.3
libncursesw6: 6.2-1
libnettle8: 3.6
libnotifications: 0.3-4
libp11-kit0: 0.23.21
libpam-modules: 186.60.1
libpam2: 20190224
libpcre1: 8.44-1
libreadline8: 8.1
libsparkcolourpicker: 1.0.2
libssh2-1: 1.9.0-2
libtasn1-6: 4.16.0-2
libundirect: 1.1
libunistring2: 0.9.10-2
libxxhash0: 0.8.0
libzstd1: 1.4.9-1
ncurses-term: 6.2-1
nmap-common: 7.91
nmap-utils: 7.91
openssh: 1:0
openssh-client: 8.5p1-1
openssh-server: 8.5p1-1
openssh-sftp-server: 8.5p1-1
sed: 4.8-2
shell-cmds: 207.40.1-2
shuffle: 1.3.1
system-cmds: 854.40.2-8
tar: 1.34
unrar: 6.0.4-1
unzip: 6.0-25
vnodebypass: 0.2.3
zip: 3.011

**Comment by arya1106** [comment]
How long does this stay for, and what were you doing right before it happened? 

It's rather strange, since the only code that changes the color of the text only runs when Jellyfish is installed, which isn't the case for you. It's possible that it was detecting a leftover file from a jellyfish installation, if you ever installed it. Could you also check `/var/lib/dpkg/info/` to see if the file `xyz.royalapps.jellyfish.list` is present there?

**Comment by L0rdLogan** [comment]
![image](https://user-images.githubusercontent.com/5092548/114677548-536bc800-9d02-11eb-8260-7c39a8f736af.png)

It doesn't stay for too long before it disappears, I haven't timed it. Tbh I'm not too bothered, it was just one of those odd things 

Since it appears to be random I can't tell you what I was doing before hand

**Comment by arya1106** [comment]
I'll be honest, I have no idea why this is happening. it's possible it could be a tweak conflict somewhere, which you'd need to find manually by disabling tweaks with icleaner. If you don't mind, i'll close this issue since it doesn't seem like a bug in the code.
