### ISSUE TITLE
Keeps alternating between short/medium since latest update

### ISSUE THREAD

**Issue by L0rdLogan** [arya1106/NappyTime14#2]
Keeps going from "Mon, March 8th" to "Monday, March 8th" on my lockscreen

**Comment by L0rdLogan** [comment]
See screenshots ![image](https://user-images.githubusercontent.com/5092548/110392557-07719780-8061-11eb-869b-51e5ae0cc4e8.jpeg)

![image](https://user-images.githubusercontent.com/5092548/110392567-0b9db500-8061-11eb-97e3-11c330b033bb.png)

**Comment by arya1106** [comment]
Looks like you're having issues with the stock date label, in the current version, I override the stock date label's text which can break a lot of lock screen tweaks. I'll be releasing an update soon with the option to use a separate label for the countdown, hopefully that solves your issue.

**Comment by L0rdLogan** [comment]
Great, thank you

**Comment by arya1106** [comment]
Hi, I'd just like to check in and make sure this was solved in the latest update.
