### ISSUE TITLE
Interfers with Jellyfish on ios 14.3

### ISSUE THREAD

**Issue by ZeyadW** [arya1106/NappyTime14#3]
Lock screen’s date becomes buggy. Although all the lock screen toggles are off. Really loving the tweak hopefully you can fix that.

**Comment by arya1106** [comment]
This is a known issue, I'm working on it, and it'll be fixed in the next update! :)

**Comment by arya1106** [comment]
Has this issue been resolved with the latest update?

**Comment by ZeyadW** [comment]
YES! Thank you! 😁
